# Generated by Django 5.2.4 on 2026-03-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_created_at_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='produit',
        ),
    ]
