# Generated by Django 5.2.4 on 2026-03-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
