# Generated by Django 5.2.4 on 2026-03-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_commande_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
