# Generated by Django 5.2.4 on 2026-03-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_commande_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
